version: '3.8'

services:
  web:
    build: .
    ports:
      - "${PORT}:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FLASK_DEBUG=${FLASK_DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - HOST=${HOST}
    depends_on:
      - db
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
